version: '3.8'
_services:
  postgres:
    image: postgres:15
    container_name: portfolio_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: portafolio_db
      POSTGRES_USER: amatap
      POSTGRES_PASSWORD: Mata1795
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  skill_service:
    build:
      context: ./skill_service
      dockerfile: Dockerfile
    image: portfolio/skill_service:latest
    container_name: skill_service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/portafolio_db
      SPRING_DATASOURCE_USERNAME: amatap
      SPRING_DATASOURCE_PASSWORD: Mata1795
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    restart: unless-stopped

  certificate_service:
    build:
      context: ./certificate_service
      dockerfile: Dockerfile
    image: portfolio/certificate_service:latest
    container_name: certificate_service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/portfolio_db
      SPRING_DATASOURCE_USERNAME: amatap
      SPRING_DATASOURCE_PASSWORD: Mata1795
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    restart: unless-stopped

  education_service:
    build:
      context: ./education_service
      dockerfile: Dockerfile
    image: portfolio/education_service:latest
    container_name: education_service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/portfolio_db
      SPRING_DATASOURCE_USERNAME: amatap
      SPRING_DATASOURCE_PASSWORD: Mata1795
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres-data:
